## This config file is for running llava over the hawaii chyron dataset using the instructions
## which were provided to the the annotators as the prompt to llava. The config is designed to 
## be run over mmif files containing swt annotations which were used to create the dataset.
## The dataset is a filtered selection of the swt-labeled chyron frames and as a result the 
## output from running this config will be a superset of the hichy dataset.

custom_prompts:
  "chyron": |
    Identify important parts of the person's name and characteristics as follows:

    In general:  Add one datum per line, skipping lines between items.

    First datum:  Copy exactly the person's name as written, including titles (such as "Miss", "Dr.", "Senator", "Rev.", etc.) and designations (such as "M.D." or "Ph.D.").  Preserve capitalization presented on screen.

    Second datum: Write the normalized form of the person's name.  Normalize capitalization, and change the order to "Lastname, Firstname" or "Lastname, Firstname Middlename, Suffix".  For example: "Murray, Patty" or "King, Martin Luther, Jr."  Do not add names, initials, characters (such as an okina), or forms of the name not used in the verbatim transcription.

    Additional data:  Copy verbatim any role, location, context, or other characteristics associated with the person, with one attribute per line.  Do not separate attributes into multiple lines unless they could be considered separate attributes of the person and are deliberately separated spatially on the screen (as with a hard line break, but not just with wrapping long lines).  In cases of multiple attributes, skip one line between them.

context_config:
  input_context: "timeframe" 

  timeframe:
    app_uri: "http://apps.clams.ai/swt-detection/"
          
    label_mapping:
      "chyron": "chyron"

    ignore_other_labels: true